export const problems =[
    {
        "id": "lrgstlmntinnrry",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 1,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Largest Element in an Array",
        "post_link": "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/",
        "yt_link": "https://youtu.be/37E9ckMDdTk?t=526",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/largest-element",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/largest-element?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "scndlrgstlmntinnrrywithtsrting",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 2,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Second Largest Element in an Array without sorting",
        "post_link": "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/",
        "yt_link": "https://youtu.be/37E9ckMDdTk?t=810",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/second-largest-element",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/second-largest-element?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "chckifthrryissrtd",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 3,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Check if the array is sorted",
        "post_link": "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/",
        "yt_link": "https://youtu.be/37E9ckMDdTk?t=17224",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/check-if-the-array-is-sorted",
        "editorial_link": " https://takeuforward.org/plus/dsa/problems/check-if-the-array-is-sorted?tab=editorial",
        "lc_link": "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/#:~:text=Input%3A%20nums%20%3D%20%5B2%2C,no%20rotation)%20to%20make%20nums.",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "rmvdplictsfrmsrtdrry",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 4,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Remove duplicates from Sorted array",
        "post_link": "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/",
        "yt_link": "https://youtu.be/37E9ckMDdTk?t=1887",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/remove-duplicates-from-sorted-array",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/remove-duplicates-from-sorted-array?tab=editorial",
        "lc_link": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/#:~:text=Input%3A%20nums%20%3D%20%5B0%2C,%2C%203%2C%20and%204%20respectively.",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "lftrttnrrybynplc",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 5,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Left Rotate an array by one place",
        "post_link": "https://takeuforward.org/data-structure/left-rotate-the-array-by-one/",
        "yt_link": "https://youtu.be/wvcQg43_V8U?t=61",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/left-rotate-array-by-one",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/left-rotate-array-by-one?tab=editorial",
        "lc_link": "https://leetcode.com/problems/rotate-array/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "lftrttnrrybydplcs",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 6,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Left rotate an array by D places",
        "post_link": "https://takeuforward.org/data-structure/rotate-array-by-k-elements/",
        "yt_link": "https://youtu.be/wvcQg43_V8U?t=485",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/left-rotate-array",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/left-rotate-array?tab=editorial",
        "lc_link": "https://leetcode.com/problems/rotate-array/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "mvzrstnd",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 7,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Move Zeros to end",
        "post_link": "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/",
        "yt_link": "https://youtu.be/wvcQg43_V8U?t=1633",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/move-zeros-to-end",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/move-zeros-to-end?tab=editorial",
        "lc_link": "https://leetcode.com/problems/move-zeroes/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"}]"
    },
    {
        "id": "linrsrch",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 8,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Linear Search",
        "post_link": "https://takeuforward.org/data-structure/linear-search-in-c/",
        "yt_link": "https://youtu.be/wvcQg43_V8U?t=2465",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/linear-search",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/linear-search?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "findthnin",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 9,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Find the Union",
        "post_link": "https://takeuforward.org/data-structure/union-of-two-sorted-arrays/",
        "yt_link": "https://youtu.be/wvcQg43_V8U?t=2584",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/union-of-two-sorted-arrays",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/union-of-two-sorted-arrays?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"sorting\",\"label\":\"Sorting\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "findmissingnmbrinnrry",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 10,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Find missing number in an array",
        "post_link": "https://takeuforward.org/arrays/find-the-missing-number-in-an-array/",
        "yt_link": "https://youtu.be/bYWLJb3vCWY?t=57",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/find-missing-number",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/find-missing-number?tab=editorial",
        "lc_link": "https://leetcode.com/problems/missing-number/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"binary-search\",\"label\":\"Binary Search\"},{\"value\":\"hashing\",\"label\":\"Hashing\"}]"
    },
    {
        "id": "mximmcnsctivns",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 11,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Maximum Consecutive Ones",
        "post_link": "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/",
        "yt_link": "https://youtu.be/bYWLJb3vCWY?t=1124",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/maximum-consecutive-ones",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/maximum-consecutive-ones?tab=editorial",
        "lc_link": "https://leetcode.com/problems/max-consecutive-ones/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "findthnmbrthtpprsncndthrnmbrstwic",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 12,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Find the number that appears once, and other numbers twice.",
        "post_link": "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/",
        "yt_link": "https://youtu.be/bYWLJb3vCWY?t=1369",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/single-number---i",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/single-number---i?tab=editorial",
        "lc_link": "https://leetcode.com/problems/single-number/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "longestsubarraywithsumpositives",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 13,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Longest subarray with given sum K(positives)",
        "post_link": "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/",
        "yt_link": "https://www.youtube.com/watch?v=frf7qxiN2qU&feature=youtu.be",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/longest-subarray-with-sum-k",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/longest-subarray-with-sum-k?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"hashing\",\"label\":\"Hashing\"}]"
    },
    {
        "id": "longestsubarraywithsumkposneg",
        "step_no": 3,
        "sub_step_no": 1,
        "sl_no": 14,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Easy",
        "question_title": "Longest subarray with sum K (Positives + Negatives)",
        "post_link": "https://takeuforward.org/arrays/longest-subarray-with-sum-k-postives-and-negatives/",
        "yt_link": "https://www.youtube.com/watch?v=frf7qxiN2qU",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/longest-subarray-with-sum-k",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/longest-subarray-with-sum-k?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"hashing\",\"label\":\"Hashing\"}]"
    },
    {
        "id": "2smprblm",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 1,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "2Sum Problem",
        "post_link": "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/",
        "yt_link": "https://youtu.be/UXDSeD9mN-k",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/two-sum",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/two-sum?tab=editorial",
        "lc_link": "https://leetcode.com/problems/two-sum/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"sorting\",\"label\":\"Sorting\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"}]"
    },
    {
        "id": "srtnrryf0s1snd2s",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 2,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Sort an array of 0's 1's and 2's",
        "post_link": "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/",
        "yt_link": "https://youtu.be/tp8JIuCXBaU",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/sort-an-array-of-0's-1's-and-2's",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/sort-an-array-of-0's-1's-and-2's?tab=editorial",
        "lc_link": "https://leetcode.com/problems/sort-colors/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "mjritylmntn2tims",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 3,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Majority Element (>n/2 times)",
        "post_link": "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/",
        "yt_link": "https://youtu.be/nP_ns3uSh80",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/majority-element-i",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/majority-element-i?tab=editorial",
        "lc_link": "https://leetcode.com/problems/majority-element/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "kdnslgrithmmximmsbrrysm",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 4,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Kadane's Algorithm, maximum subarray sum",
        "post_link": "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",
        "yt_link": "https://youtu.be/AHZpyENo7k4?si=QJpof4R1hHokm1hw",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/kadane's-algorithm",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/kadane's-algorithm?tab=editorial",
        "lc_link": "https://leetcode.com/problems/maximum-subarray/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "printsbrrywithmximmsbrrysmxtnddvrsinfbvprblm",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 5,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Print subarray with maximum subarray sum (extended version of above problem)",
        "post_link": "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",
        "yt_link": "https://youtu.be/AHZpyENo7k4",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/kadane's-algorithm",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/kadane's-algorithm?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "stckbyndsll",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 6,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Stock Buy and Sell",
        "post_link": "https://takeuforward.org/data-structure/stock-buy-and-sell/",
        "yt_link": "https://youtu.be/excAOvwF_Wk",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/best-time-to-buy-and-sell-stock",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/best-time-to-buy-and-sell-stock?tab=editorial",
        "lc_link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "rrrngthrryinltrntingpsitivndngtivitms",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 7,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Rearrange the array in alternating positive and negative items",
        "post_link": "https://takeuforward.org/arrays/rearrange-array-elements-by-sign/",
        "yt_link": "https://youtu.be/h4aBagy4Uok",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/rearrange-array-elements-by-sign",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/rearrange-array-elements-by-sign?tab=editorial",
        "lc_link": "https://leetcode.com/problems/rearrange-array-elements-by-sign/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "nxtprmttin",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 8,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Next Permutation",
        "post_link": "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/",
        "yt_link": "https://youtu.be/JDOXKqF60RQ",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/next-permutation",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/next-permutation?tab=editorial",
        "lc_link": "https://leetcode.com/problems/next-permutation/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"},{\"value\":\"two-pointers\",\"label\":\"Two Pointer\"}]"
    },
    {
        "id": "ldrsinnrryprblm",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 9,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Leaders in an Array problem",
        "post_link": "https://takeuforward.org/data-structure/leaders-in-an-array/",
        "yt_link": "https://youtu.be/cHrH9CQ8pmY",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/leaders-in-an-array",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/leaders-in-an-array?tab=editorial",
        "lc_link": null,
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "lngstcnsctivsqncinnrry",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 10,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Longest Consecutive Sequence in an Array",
        "post_link": "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/",
        "yt_link": "https://youtu.be/oO5uLE7EUlM",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/longest-consecutive-sequence-in-an-array",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/longest-consecutive-sequence-in-an-array?tab=editorial",
        "lc_link": "https://leetcode.com/problems/longest-consecutive-sequence/solution/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "stmtrixzrs",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 11,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Set Matrix Zeros",
        "post_link": "https://takeuforward.org/data-structure/set-matrix-zero/",
        "yt_link": "https://youtu.be/N0MgLvceX7M",
        "plus_link": null,
        "editorial_link": null,
        "lc_link": "https://leetcode.com/problems/set-matrix-zeroes/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "rttmtrixby90dgrs",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 12,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Rotate Matrix by 90 degrees",
        "post_link": "https://takeuforward.org/data-structure/rotate-image-by-90-degree/",
        "yt_link": "https://youtu.be/Z0R2u6gd3GU",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/rotate-matrix-by-90-degrees",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/rotate-matrix-by-90-degrees?tab=editorial",
        "lc_link": "https://leetcode.com/problems/rotate-image/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "printthmtrixinspirlmnnr",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 13,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Print the matrix in spiral manner",
        "post_link": "https://takeuforward.org/data-structure/spiral-traversal-of-matrix/",
        "yt_link": "https://youtu.be/3Zv-s9UUrFM",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/print-the-matrix-in-spiral-manner",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/print-the-matrix-in-spiral-manner?tab=editorial",
        "lc_link": "https://leetcode.com/problems/spiral-matrix/",
        "company_tags": null,
        "difficulty": 1,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    },
    {
        "id": "sbrrywithgivnsm",
        "step_no": 3,
        "sub_step_no": 2,
        "sl_no": 14,
        "step_title": "Solve Problems on Arrays [Easy -> Medium -> Hard]",
        "sub_step_title": "Medium",
        "question_title": "Count subarrays with given sum",
        "post_link": "https://takeuforward.org/arrays/count-subarray-sum-equals-k/",
        "yt_link": "https://www.youtube.com/watch?v=xvNwoz-ufXA&list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz&index=32",
        "plus_link": "https://takeuforward.org/plus/dsa/problems/count-subarrays-with-given-sum",
        "editorial_link": "https://takeuforward.org/plus/dsa/problems/count-subarrays-with-given-sum?tab=editorial",
        "lc_link": "https://leetcode.com/problems/subarray-sum-equals-k/",
        "company_tags": null,
        "difficulty": 0,
        "ques_topic": "[{\"value\":\"arrays\",\"label\":\"Arrays\"},{\"value\":\"hashing\",\"label\":\"Hashing\"},{\"value\":\"data-structure\",\"label\":\"Data Structures\"}]"
    }
]